### PR TITLE
Fanout language updates

### PR DESCRIPTION
**Pull request by mgloystein**

### CODE REVIEW

**Comment by GregBowyer** [comment]
Hi there I see you closed this, could you open it on GregBowyer/planout-golang ?

**Comment by mgloystein** [comment]
Thanks @GregBowyer for taking a look, but it was meant only go to our fork for now. We're working with a slightly modified version of the planout language and needed some revisions to accommodate. Our plan is it vet it in our system for a few weeks before exposing it to the general public. If you'd like to track what we're doing with it here https://github.com/Fanatics/planout-golang.

**Comment by eytan** [comment]
Michael, if you are thinking of making any modifications to the PlanOut language I would love to learn more about your use case and see if it is something we should be adding to the reference implementation.

**Comment by eytan** [comment]
@mgloystein, @GregBowyer, I wonder if this (kind of) recent change to the PlanOut does something similar to your dynamic operator patch: https://github.com/facebook/planout/commit/53b5bd6ce1a6cda65a0c42fc7582fb80c0d9707b. If so it might be good to try to emulate the API as much as possible to maintain consistency across the different ports.

In general I would love to be able to make PlanOut work well for everybody's use case, so if you have any ideas for extensions I'd be happy to discuss them and see if / how we can add them to the reference implementation.

**Comment by mgloystein** [comment]
@eytan, yeah it looks like it's doing something very similar, just putting the operations on the interpreter instance instead. I didn't want to change it to dramatically, so I went for the smallest change. There's also a second piece, getting and setting values that are deeper in the output object. Our use case requires some fairly complex objects to returned as settings, and at times only one or two values in those objects need to be overridden.

**Pull request closed without merging**
