### PR TITLE
Implement namespace code running

### PR DESCRIPTION
**Pull request by GregBowyer**
Thoughts ? 

@tsujeeth I think this is what we need to make namespaces work.

I hid away most of SimpleNamespace as there is IMHO a bunch of stuff there that is specific to that implementation.

I made a generic Run() interface that I think should cover both Namespace and Interpreter.

I am with @eytan, we should sort out the m map, Salt and Outputs a bit, its a tad confused what belongs to what and what the caller should provide and what the callee provides.

@eytan from what I can ascertain namespace is bound to a primary unit (e.g. userid) with each experiment getting allocated to buckets in that namespace. If two experiments get allocated to the same segment, the first one in wins? This would mean that for the primary unit, per namespace, one experiment runs for an allocation ?

### CODE REVIEW

**Comment by tsujeeth** [comment]
Thanks @GregBowyer for the fixes. The changes looks good.

- "If two experiments get allocated to the same segment ..."

From what I understand, two experiments cannot get allocated to the same segment. Experiments are always assigned to segments that are available.

For example, say `total segments` = 5, `expt1` needs 2, `expt2` needs 2. Before any allocation, `available segments` = `[0, 1, 2, 3, 4]`. First we allocate segments for `expt1`; say they take segments `[1, 3]`. Now, `available segments` is now `[0, 2, 4]`. Segments for `expt2` will now be allocated from this remainder; say they take `[2, 4]`. So we are left with: `expt1` allocated segments `[1, 3]`, `expt2` allocated segments `[2, 4]`, segment 0 (more generally, any unallocated segment) is assigned the `default experiment`.

- "one experiment runs for an allocation ..."

Yep.

**Comment by eytan** [comment]
^ what @tsujeeth said. Namespaces are for running mutually exclusive experiments - there is no competition :) The most common use case for namespaces are for ranking experiments, where there is only one way to sort items.  However, most experiments don't need to be mutually exclusive, and so its often best to think of namespaces as a way of safely running follow-on experiments or slowly rolling out a feature or test.  I often tell people that as a rule of thumb, if their experiments aren't setting the same variable in their source code (e.g., as one would when setting the parameters or model ID of a ranking algorithm), they probably don't belong in the same namespace.

**Comment by GregBowyer** [comment]
^^ You both echoed what I thought, I was wording it badly

**Comment by tsujeeth** [comment]
^^ Thanks @eytan

**Pull request merged**
